Update 110-third-party-integrations.mdx
printtracker/docs pull request #41
Opened 2023-07-07 13:48 UTC by zaha-eco

Hey Clark,

Found these errors after commiting:
line 79 
As integrações que exigem o uso de uma chave de API, como o [Processador de Dados do Print Tracker](#e-automatizar) ou quaisquer integrações personalizadas usando a [API REST](#rest-api) incorrem em encargos adicionais que aparecerão na sua fatura mensal.

line 30
O Tigerpaw suporta a ingestão de dados do medidor por meio de arquivos CSV enviados por e-mail. Você pode criar um [relatório personalizado](./reports) para ser enviado por e-mail para a Tigerpaw.

2023-07-07 14:21 UTC, clarkmcc commented
@zaha-eco I may be misreading, but it looks like those edits are the same as the files. Is that true?

2023-07-07 14:32 UTC, zaha-eco commented
@clarkmcc please ignore line 30. 

I did translate the (e-automate) by mistake on line 79.

2023-07-11 20:51 UTC, clarkmcc requested changes
@zaha-eco here is the suggested change

2023-07-11 21:04 UTC, clarkmcc approved these changes

2023-07-11 21:04 UTC, merged